### PR TITLE
[HOPSWORKS-1079] Integrate sparkmagic with maggy

### PR DESCRIPTION
**Pull request by jimdowling**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1079

### CODE REVIEW

**Review by moritzmeister — CHANGES_REQUESTED** [review]
`from hops import tls`,
`import os` and
`from pyspark.sql import SparkSession`
can be removed from the imports.

You are defining `_send_request` but actually using `util.send_request`. Did we mean to delete `_send_request` and use the hops.util one?

There is one inconsistency with the constants:
`from hops import constants`
can you change it to
`from hops import constants as hopsconstants` and replace it in the code :)
And if we plan to use `_send_request` then in the _send_request there's still `hopster` which should be `hopsconstants` then, too. Furthermore, then we need to import `get_jwt` or use `hopsutil.get_jwt()`

Thanks!

**Comment by jimdowling** [comment]
Loads of bugs! Sorry, it was sloppy. I fixed them now.
We shouldn't re-implement hops-util-py methods here - only in sparkmagic, because that doesn't have a spark context, so you can't use all modules in the hops libraries.

**Review by moritzmeister — CHANGES_REQUESTED** [review]
No worries, thanks for the changes!
One more thing, now you just need to change `constants` to `hopsconstants` down in the `resource_url` etc.

you can also remove the
`from pyspark.sql import SparkSession`
since we are using the hopsutil, or do I miss something?

**Review by moritzmeister — APPROVED** [review]

**Review by moritzmeister — COMMENTED** [review]
Thanks Jim! sorry for bothering you

**Comment by jimdowling** [comment]
No bother, i love coding (don't tell my board :) )

**Pull request merged**
